(require 'haskell-mode)
(require 'haskell-cabal)
(add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
(add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
(add-hook 'haskell-mode-hook 'font-lock-mode)
(add-hook 'haskell-mode-hook 'imenu-add-menubar-index)
(add-to-list 'auto-mode-alist '("\\.hs$" . haskell-mode))
